# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/umuti/Desktop/FFendeksçekme/veriçekme.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1078, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/list.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.cmb_ilk_yil = QtWidgets.QComboBox(self.groupBox_3)
        self.cmb_ilk_yil.setObjectName("cmb_ilk_yil")
        self.verticalLayout_3.addWidget(self.cmb_ilk_yil)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cmb_tml_yil = QtWidgets.QComboBox(self.groupBox_4)
        self.cmb_tml_yil.setObjectName("cmb_tml_yil")
        self.horizontalLayout_2.addWidget(self.cmb_tml_yil)
        self.cmb_tml_ay = QtWidgets.QComboBox(self.groupBox_4)
        self.cmb_tml_ay.setObjectName("cmb_tml_ay")
        self.horizontalLayout_2.addWidget(self.cmb_tml_ay)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit.setEnabled(False)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.btn_vericek = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_vericek.setObjectName("btn_vericek")
        self.verticalLayout_4.addWidget(self.btn_vericek)
        self.btn_fiyatfark = QtWidgets.QPushButton(self.groupBox_5)
        self.btn_fiyatfark.setObjectName("btn_fiyatfark")
        self.verticalLayout_4.addWidget(self.btn_fiyatfark)
        self.open_excel = QtWidgets.QPushButton(self.groupBox_5)
        self.open_excel.setObjectName("open_excel")
        self.verticalLayout_4.addWidget(self.open_excel)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_fiyat_farki = QtWidgets.QTableWidget(self.groupBox_2)
        self.tbl_fiyat_farki.setObjectName("tbl_fiyat_farki")
        self.tbl_fiyat_farki.setColumnCount(0)
        self.tbl_fiyat_farki.setRowCount(0)
        self.verticalLayout.addWidget(self.tbl_fiyat_farki)
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout.setStretch(0, 35)
        self.horizontalLayout.setStretch(1, 65)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1078, 21))
        self.menubar.setObjectName("menubar")
        self.menuDosya = QtWidgets.QMenu(self.menubar)
        self.menuDosya.setObjectName("menuDosya")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStatusTip("")
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAyarlar = QtWidgets.QAction(MainWindow)
        self.actionAyarlar.setObjectName("actionAyarlar")
        self.actionHakk_nda = QtWidgets.QAction(MainWindow)
        self.actionHakk_nda.setObjectName("actionHakk_nda")
        self.actionYard_m = QtWidgets.QAction(MainWindow)
        self.actionYard_m.setObjectName("actionYard_m")
        self.menuDosya.addAction(self.actionAyarlar)
        self.menuDosya.addAction(self.actionYard_m)
        self.menuDosya.addAction(self.actionHakk_nda)
        self.menubar.addAction(self.menuDosya.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fiyat Farkı Endekslerini Tablosu"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Güncel Endeksler"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Temel Endeks"))
        self.lineEdit.setText(_translate("MainWindow", "1,00"))
        self.btn_vericek.setText(_translate("MainWindow", "Verileri Çek"))
        self.btn_fiyatfark.setText(_translate("MainWindow", "Hesapla"))
        self.open_excel.setText(_translate("MainWindow", "Excel Dosyasını Aç"))
        self.menuDosya.setTitle(_translate("MainWindow", "Dosya"))
        self.actionAyarlar.setText(_translate("MainWindow", "Ayarlar"))
        self.actionHakk_nda.setText(_translate("MainWindow", "Hakkında"))
        self.actionYard_m.setText(_translate("MainWindow", "Yardım"))

import images_rc
